[tools]
neovim = "nightly"
lazydocker = "latest"
go = "latest"
ripgrep = "latest"
fzf = "latest"
fd = "latest"
awscli = "latest"
lua = "latest"
rust = "latest"
yarn = "latest"
dotnet = "8.0.100-preview.7.23376.3"
delta = "latest"
